IOP-1415-no-patient-read-scope-logs
icanbwell/helix.fhir.client.sdk pull request #86
Opened 2024-03-27 16:25 UTC by drew-bwell

Changes associated with [IOP-1415](https://icanbwell.atlassian.net/browse/IOP-1415), specifically:

1. Adding warnings when `scopes` are parsed and do not include `read` permissions for patient demographic information
2. Adding a check during scope parsing for whenever the `launch/patient` scope is included that a corresponding `patient/xxx` scope is also included, and if not removing the unused `launch/patient` scope
3. Associated tests

2024-04-10 13:35 UTC, cdukebwell requested changes
Can you please separate out the Patient scope logic from the regular logic in tests? 

We still want to ensure the non-patient logic works as expected and it appears we have modified the tests for standard interaction to be patient-centric and not all fhir servers we interact with require that sort of scope. 

As the SMART on FHIR launch and scope pattern set forth bby hl7 is seen as more than a suggestion than a rule sometimes what happens if a vendor decides to use something other than patient/ or user/? can we adapt for that if it occurs?

2024-04-10 15:50 UTC, drew-bwell commented
> Can you please separate out the Patient scope logic from the regular logic in tests?
> 
> We still want to ensure the non-patient logic works as expected and it appears we have modified the tests for standard interaction to be patient-centric and not all fhir servers we interact with require that sort of scope.
> 
> As the SMART on FHIR launch and scope pattern set forth bby hl7 is seen as more than a suggestion than a rule sometimes what happens if a vendor decides to use something other than patient/ or user/? can we adapt for that if it occurs?

@cdukebwell just to confirm:

1. Looking at this again after a few weeks (and being a smidge more familiar with the technical landscape), would it be more appropriate move [the patient demographic read permission check (and relevant warnings for missing `Patient.read` permissions)](https://github.com/icanbwell/helix.fhir.client.sdk/pull/86/files#diff-92ebb10ec13d91263d91c52f9a9eba29fb5f154ce0f978393388f671da28f4c6R122) out of the `helix_fhir_client_sdk` and into the `patient_access_pipeline` (specifically, [somewhere like here in `patient_access_fhir_retriever`](https://github.com/icanbwell/helix.pipelines/blob/0efe9dd7a3b4f35746f018b4dd3c5357b30e93ec/transformers/patient_access_transformer/v4/helpers/retrievers/patient_access_fhir_retriever.py#L152), when a given patient's data is being retrieved)? When I initially put this together, I selfishly didn't account for non-PROA use-cases within the SDK :)

2. The meat of the previously available tests have not been changed (i.e., scopes being tested and how they're tested), changes include:
    1.  [Some formatting tweaks](https://github.com/icanbwell/helix.fhir.client.sdk/pull/86/files#diff-3a67aacf552dd5531f09b6cefe1ef3ec7801f846a730ae60166d77ba89a476b5R7) (per `black`)
    3. [More descriptive names](https://github.com/icanbwell/helix.fhir.client.sdk/pull/86/files#diff-3a67aacf552dd5531f09b6cefe1ef3ec7801f846a730ae60166d77ba89a476b5R4) (e.g., `test_fhir_scope_parser_correct_allow()` --> `test_fhir_scope_parser_correct_patient_allow()` to contrast with the new `test_fhir_scope_parser_correct_user_allow()` which tests allowing `user/` scopes)
    4. [`FhirScopeParser.parse_scopes()` no longer being a `staticmethod`](https://github.com/icanbwell/helix.fhir.client.sdk/pull/86/files#diff-f73e73b8929b5ad44ac09549421d861f16c3efb11b091d564e41f359493169ceR11)
    5. New tests ([handling `user/` scopes](https://github.com/icanbwell/helix.fhir.client.sdk/pull/86/files#diff-3a67aacf552dd5531f09b6cefe1ef3ec7801f846a730ae60166d77ba89a476b5R39), [removing unused `launch/patient` scope](https://github.com/icanbwell/helix.fhir.client.sdk/pull/86/files#diff-f73e73b8929b5ad44ac09549421d861f16c3efb11b091d564e41f359493169ceR149))
   
    In light of that, for "the regular logic in tests", would it be appropriate to create new tests for scopes not included in this PR (i.e., non-`patient/` and non-`user/`), as the previous tests ([`test_fhir_scope_parser_can_parse_scopes()`](https://github.com/icanbwell/helix.fhir.client.sdk/blob/d18e9eeb91ae3fe5a1c558039aa50b626476b0d5/helix_fhir_client_sdk/utilities/test/test_fhir_scope_parser_can_parse_scopes.py#L9), [`test_fhir_scope_parser_correct_allow()`](https://github.com/icanbwell/helix.fhir.client.sdk/blob/d18e9eeb91ae3fe5a1c558039aa50b626476b0d5/helix_fhir_client_sdk/utilities/test/test_fhir_scope_parser_correct_allow.py#L4)) tested almost exclusively `patient/` scopes?

3. In this PR, the parser will default to allowing an interaction if neither `patient/` nor `user/` scopes are defined in `parsed_scopes` ([here](https://github.com/icanbwell/helix.fhir.client.sdk/pull/86/files#diff-92ebb10ec13d91263d91c52f9a9eba29fb5f154ce0f978393388f671da28f4c6R152)). Currently (in `master`), any interaction is allowed if no `patient` scopes are defined in `parsed_scopes`
    1. It appears this is the root cause of [IOP-1389](https://icanbwell.atlassian.net/browse/IOP-1389), as in that case there were no `Patient.read` permissions in a given set of `parsed_scopes`, however since the scopes that _were_ there were defined using `user/` (i.e., no `patient/` scopes). 
    
    In the case of a vendor not utilizing `patient/` or `user/` scopes, interactions will default to being allowed by `FhirScopeParser`

2024-04-11 15:52 UTC, drew-bwell commented
> > Can you please separate out the Patient scope logic from the regular logic in tests?
> > We still want to ensure the non-patient logic works as expected and it appears we have modified the tests for standard interaction to be patient-centric and not all fhir servers we interact with require that sort of scope.
> > As the SMART on FHIR launch and scope pattern set forth bby hl7 is seen as more than a suggestion than a rule sometimes what happens if a vendor decides to use something other than patient/ or user/? can we adapt for that if it occurs?
> 
> @cdukebwell just to confirm:
> 
> 1. Looking at this again after a few weeks (and being a smidge more familiar with the technical landscape), would it be more appropriate move [the patient demographic read permission check (and relevant warnings for missing `Patient.read` permissions)](https://github.com/icanbwell/helix.fhir.client.sdk/pull/86/files#diff-92ebb10ec13d91263d91c52f9a9eba29fb5f154ce0f978393388f671da28f4c6R122) out of the `helix_fhir_client_sdk` and into the `patient_access_pipeline` (specifically, [somewhere like here in `patient_access_fhir_retriever`](https://github.com/icanbwell/helix.pipelines/blob/0efe9dd7a3b4f35746f018b4dd3c5357b30e93ec/transformers/patient_access_transformer/v4/helpers/retrievers/patient_access_fhir_retriever.py#L152), when a given patient's data is being retrieved)? When I initially put this together, I selfishly didn't account for non-PROA use-cases within the SDK :)
> 2. The meat of the previously available tests have not been changed (i.e., scopes being tested and how they're tested), changes include:
>    
>    1. [Some formatting tweaks](https://github.com/icanbwell/helix.fhir.client.sdk/pull/86/files#diff-3a67aacf552dd5531f09b6cefe1ef3ec7801f846a730ae60166d77ba89a476b5R7) (per `black`)
>    2. [More descriptive names](https://github.com/icanbwell/helix.fhir.client.sdk/pull/86/files#diff-3a67aacf552dd5531f09b6cefe1ef3ec7801f846a730ae60166d77ba89a476b5R4) (e.g., `test_fhir_scope_parser_correct_allow()` --> `test_fhir_scope_parser_correct_patient_allow()` to contrast with the new `test_fhir_scope_parser_correct_user_allow()` which tests allowing `user/` scopes)
>    3. [`FhirScopeParser.parse_scopes()` no longer being a `staticmethod`](https://github.com/icanbwell/helix.fhir.client.sdk/pull/86/files#diff-f73e73b8929b5ad44ac09549421d861f16c3efb11b091d564e41f359493169ceR11)
>    4. New tests ([handling `user/` scopes](https://github.com/icanbwell/helix.fhir.client.sdk/pull/86/files#diff-3a67aacf552dd5531f09b6cefe1ef3ec7801f846a730ae60166d77ba89a476b5R39), [removing unused `launch/patient` scope](https://github.com/icanbwell/helix.fhir.client.sdk/pull/86/files#diff-f73e73b8929b5ad44ac09549421d861f16c3efb11b091d564e41f359493169ceR149))
>    
>    In light of that, for "the regular logic in tests", would it be appropriate to create new tests for scopes not included in this PR (i.e., non-`patient/` and non-`user/`), as the previous tests ([`test_fhir_scope_parser_can_parse_scopes()`](https://github.com/icanbwell/helix.fhir.client.sdk/blob/d18e9eeb91ae3fe5a1c558039aa50b626476b0d5/helix_fhir_client_sdk/utilities/test/test_fhir_scope_parser_can_parse_scopes.py#L9), [`test_fhir_scope_parser_correct_allow()`](https://github.com/icanbwell/helix.fhir.client.sdk/blob/d18e9eeb91ae3fe5a1c558039aa50b626476b0d5/helix_fhir_client_sdk/utilities/test/test_fhir_scope_parser_correct_allow.py#L4)) tested almost exclusively `patient/` scopes?
> 3. In this PR, the parser will default to allowing an interaction if neither `patient/` nor `user/` scopes are defined in `parsed_scopes` ([here](https://github.com/icanbwell/helix.fhir.client.sdk/pull/86/files#diff-92ebb10ec13d91263d91c52f9a9eba29fb5f154ce0f978393388f671da28f4c6R152)). Currently (in `master`), any interaction is allowed if no `patient` scopes are defined in `parsed_scopes`
>    
>    1. It appears this is the root cause of [IOP-1389](https://icanbwell.atlassian.net/browse/IOP-1389), as in that case there were no `Patient.read` permissions in a given set of `parsed_scopes`, however since the scopes that _were_ there were defined using `user/` (i.e., no `patient/` scopes).
>    
>    In the case of a vendor not utilizing `patient/` or `user/` scopes, interactions will default to being allowed by `FhirScopeParser`

Per conversation with @cdukebwell:
1. Move `patient` demographic read permission checks and warnings (point 1 above) to PROA pipeline
   1. Update [`helix.fhir.client.sdk`](https://github.com/icanbwell/helix.pipelines) version in helix.pipelines once released
3. Add test for scope parser where there are no `user/` or `patient/` scopes, and test for `system/` scopes

2024-04-16 14:34 UTC, cdukebwell approved these changes

2024-04-16 14:43 UTC, merged